sudo: required
# Chrome is no longer supported on Ubuntu Precise (12.04), so use Trusty (14.04).
dist: trusty

language: java
before_install: git log --oneline -n 5
install:
  - sudo ./install-build-deps.sh
script:
  # Use system python for protobuf package.
  - export PATH='/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin'
  - hooks/pre-commit
  - ant test -Dtest.shuffle=1 -Dtest.repeat=10
  - ant package
env:
  - CHROME_MIN_VERSION=49
  - CHROME_MIN_VERSION=99
